### PR TITLE
ft: populate dashboard with transaction history

### PR DESCRIPTION
**Pull request by aapetsi**
## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aapetsi** [comment]
[Populate the dashboard with total earnings and sales history](https://trello.com/c/L4zhRWwX/158-populate-the-dashboard-with-total-earnings-and-sales-history)

**Review by shaunorpen — CHANGES_REQUESTED** [review]
@aapetsi Can you merge in develop before we review / approve? Thanks!

**Review by shaunorpen — CHANGES_REQUESTED** [review]
A few things I'd like to suggest updating before we merge:

Log in as me (447791750439 / Password), and checkout:

1. Use currency symbol instead of currency acronym. E.g. on my dashboard it says I've sold POU0 this month. I think it's better to say £0. The currency symbol is already available on the page as {sign}.

2. The layout of the first item in sales history looks a little odd, and the amounts could do with a currency symbol too. You should be able to use the same {sign} as above. There's also a third item with no content?

3. There's something not quite right with the CSS. The navbar should be fixed to the bottom of the screen but moves up and down slightly when I scroll. 

Cheers!

**Review by shaunorpen — APPROVED** [review]
Great work!

**Pull request merged**
