### PR TITLE
FX: Update support page styling

### PR DESCRIPTION
**Pull request by shaunorpen**
## Description
The support page didn't look good. Now it does!
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/OIWTHJYA/197-update-support-page-styling

### CODE REVIEW

**Comment by shaunorpen** [comment]
[Update support page styling](https://trello.com/c/OIWTHJYA/197-update-support-page-styling)

**Review by aapetsi — COMMENTED** [review]
Good job. One thing:
Can you make the gap between the button and the remaining text smaller

**Comment by shaunorpen** [comment]
@aapetsi Done. Please re-review!

**Review by aapetsi — APPROVED** [review]
Good job done!

**Pull request merged**
