### PR TITLE
FX: Polish front end

### PR DESCRIPTION
**Pull request by shaunorpen**
## Description
Various updates. See Trello card for detail.
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/O69x7JOT/141-polish-front-end

### CODE REVIEW

**Comment by shaunorpen** [comment]
[Polish: Front End](https://trello.com/c/O69x7JOT/141-polish-front-end)

**Comment by shaunorpen** [comment]
[Polish: Front End](https://trello.com/c/O69x7JOT/141-polish-front-end)

**Comment by shaunorpen** [comment]
[Polish: Front End](https://trello.com/c/O69x7JOT/141-polish-front-end)

**Comment by shaunorpen** [comment]
[Polish: Front End](https://trello.com/c/O69x7JOT/141-polish-front-end)

**Review by DimejiAre — APPROVED** [review]
Good Job!!

**Pull request merged**
