### PR TITLE
ft: add pwa functionality

### PR DESCRIPTION
**Pull request by tolls-3**
## Description
Setup PWA functionality on the web app
## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/cxhl3nUJ/156-make-shopping-cart-app-a-progressive-web-app

### CODE REVIEW

**Comment by tolls-3** [comment]
[Make Shopping cart app a Progressive Web App](https://trello.com/c/cxhl3nUJ/156-make-shopping-cart-app-a-progressive-web-app)

**Comment by tolls-3** [comment]
>  [Make Shopping cart app a Progressive Web App](https://trello.com/c/cxhl3nUJ/156-make-shopping-cart-app-a-progressive-web-app)

**Review by aapetsi — APPROVED** [review]
Good stuff!!

**Review by aapetsi — COMMENTED** [review]
The logo doesn't show on the dashboard page and the profile page

**Pull request merged**
