### PR TITLE
FT: Add cart header

### PR DESCRIPTION
**Pull request by shaunorpen**
## Description
Add cart header component. 
The new component can be accessed for testing purposes at: `/elements/cartheader`
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/hLDYryfS/113-cart-header-component

### CODE REVIEW

**Comment by shaunorpen** [comment]
[Cart Header Component](https://trello.com/c/hLDYryfS/113-cart-header-component)

**Comment by shaunorpen** [comment]
Further updates to make: 
1. Add back button on top left.
2. Make total a conditional display item.

**Review by kip-guile — APPROVED** [review]
Looks good

**Review by tolls-3 — APPROVED** [review]
All looks good.

**Pull request merged**
