### PR TITLE
FT: Add custom 404 page

### PR DESCRIPTION
**Pull request by shaunorpen**
## Description
Add a custom 404 page.
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/durqdxKV/193-display-a-404-error-page-if-the-does-not-exists

### CODE REVIEW

**Comment by shaunorpen** [comment]
[Display a 404 error page if the does not exists](https://trello.com/c/durqdxKV/193-display-a-404-error-page-if-the-does-not-exists)

**Review by aapetsi — COMMENTED** [review]
Can you reduce the gap between the login button and the remaining text at the top

**Comment by shaunorpen** [comment]
@aapetsi Done. Please re-review!

**Review by aapetsi — APPROVED** [review]
Looks good!

**Pull request merged**
