### PR TITLE
FT: Request password reset

### PR DESCRIPTION
**Pull request by shaunorpen**
## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/0ZQqpQdq/27-create-reset-password-page

### CODE REVIEW

**Review by aapetsi — APPROVED** [review]
Everything looks fine

**Comment by Rexben001** [comment]
@shaunorpen The login and register page for your branch is not working https://deploy-preview-19--shopping-cart-eu3.netlify.com/login but it's working for the last PR  https://deploy-preview-18--shopping-cart-eu3.netlify.com/login

**Comment by shaunorpen** [comment]
@Rexben001 No idea why that would be. I didn't change anything related to those pages I don't think?

**Comment by shaunorpen** [comment]
Fixed by merging develop branch into this one...

**Pull request merged**
