### PR TITLE
ch: add desktop layout for create store page

### PR DESCRIPTION
**Pull request by aapetsi**
## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aapetsi** [comment]
[Desktop view for creating a store](https://trello.com/c/4HUVIh0q/139-desktop-view-for-creating-a-store)

**Review by tolls-3 — COMMENTED** [review]
There is an issue with add Logo component, when uploading a picture it does not stay in place.

**Comment by tolls-3** [comment]
> There is an issue with add Logo component, when uploading a picture it does not stay in place.

**Comment by tolls-3** [comment]
All good now!

**Pull request merged**
